<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' => 'Afghanistan', 'code_alpha_2' => 'AF', 'code_alpha_3' => 'AFG', 'code_un' => '004'],
            ['name' => 'Aland Islands', 'code_alpha_2' => 'AX', 'code_alpha_3' => 'ALA', 'code_un' => '248'],
            ['name' => 'Albania', 'code_alpha_2' => 'AL', 'code_alpha_3' => 'ALB', 'code_un' => '008'],
            ['name' => 'Algeria', 'code_alpha_2' => 'DZ', 'code_alpha_3' => 'DZA', 'code_un' => '012'],
            ['name' => 'American Samoa', 'code_alpha_2' => 'AS', 'code_alpha_3' => 'ASM', 'code_un' => '016'],
            ['name' => 'Andorra', 'code_alpha_2' => 'AD', 'code_alpha_3' => 'AND', 'code_un' => '020'],
            ['name' => 'Angola', 'code_alpha_2' => 'AO', 'code_alpha_3' => 'AGO', 'code_un' => '024'],
            ['name' => 'Anguilla', 'code_alpha_2' => 'AI', 'code_alpha_3' => 'AIA', 'code_un' => '660'],
            ['name' => 'Antarctica', 'code_alpha_2' => 'AQ', 'code_alpha_3' => 'ATA', 'code_un' => '010'],
            ['name' => 'Antigua and Barbuda', 'code_alpha_2' => 'AG', 'code_alpha_3' => 'ATG', 'code_un' => '028'],
            ['name' => 'Argentina', 'code_alpha_2' => 'AR', 'code_alpha_3' => 'ARG', 'code_un' => '032'],
            ['name' => 'Armenia', 'code_alpha_2' => 'AM', 'code_alpha_3' => 'ARM', 'code_un' => '051'],
            ['name' => 'Aruba', 'code_alpha_2' => 'AW', 'code_alpha_3' => 'ABW', 'code_un' => '533'],
            ['name' => 'Australia', 'code_alpha_2' => 'AU', 'code_alpha_3' => 'AUS', 'code_un' => '036'],
            ['name' => 'Austria', 'code_alpha_2' => 'AT', 'code_alpha_3' => 'AUT', 'code_un' => '040'],
            ['name' => 'Azerbaijan', 'code_alpha_2' => 'AZ', 'code_alpha_3' => 'AZE', 'code_un' => '031'],
            ['name' => 'Bahamas', 'code_alpha_2' => 'BS', 'code_alpha_3' => 'BHS', 'code_un' => '044'],
            ['name' => 'Bahrain', 'code_alpha_2' => 'BH', 'code_alpha_3' => 'BHR', 'code_un' => '048'],
            ['name' => 'Bangladesh', 'code_alpha_2' => 'BD', 'code_alpha_3' => 'BGD', 'code_un' => '050'],
            ['name' => 'Barbados', 'code_alpha_2' => 'BB', 'code_alpha_3' => 'BRB', 'code_un' => '052'],
            ['name' => 'Belarus', 'code_alpha_2' => 'BY', 'code_alpha_3' => 'BLR', 'code_un' => '112'],
            ['name' => 'Belgium', 'code_alpha_2' => 'BE', 'code_alpha_3' => 'BEL', 'code_un' => '056'],
            ['name' => 'Belize', 'code_alpha_2' => 'BZ', 'code_alpha_3' => 'BLZ', 'code_un' => '084'],
            ['name' => 'Benin', 'code_alpha_2' => 'BJ', 'code_alpha_3' => 'BEN', 'code_un' => '204'],
            ['name' => 'Bermuda', 'code_alpha_2' => 'BM', 'code_alpha_3' => 'BMU', 'code_un' => '060'],
            ['name' => 'Bhutan', 'code_alpha_2' => 'BT', 'code_alpha_3' => 'BTN', 'code_un' => '064'],
            ['name' => 'Bolivia', 'code_alpha_2' => 'BO', 'code_alpha_3' => 'BOL', 'code_un' => '068'],
            ['name' => 'Bosnia and Herzegovina', 'code_alpha_2' => 'BA', 'code_alpha_3' => 'BIH', 'code_un' => '070'],
            ['name' => 'Botswana', 'code_alpha_2' => 'BW', 'code_alpha_3' => 'BWA', 'code_un' => '072'],
            ['name' => 'Bouvet Island', 'code_alpha_2' => 'BV', 'code_alpha_3' => 'BVT', 'code_un' => '074'],
            ['name' => 'Brazil', 'code_alpha_2' => 'BR', 'code_alpha_3' => 'BRA', 'code_un' => '076'],
            ['name' => 'British Virgin Islands', 'code_alpha_2' => 'VG', 'code_alpha_3' => 'VGB', 'code_un' => '092'],
            ['name' => 'British Indian Ocean Territory', 'code_alpha_2' => 'IO', 'code_alpha_3' => 'IOT', 'code_un' => '086'],
            ['name' => 'Brunei Darussalam', 'code_alpha_2' => 'BN', 'code_alpha_3' => 'BRN', 'code_un' => '096'],
            ['name' => 'Bulgaria', 'code_alpha_2' => 'BG', 'code_alpha_3' => 'BGR', 'code_un' => '100'],
            ['name' => 'Burkina Faso', 'code_alpha_2' => 'BF', 'code_alpha_3' => 'BFA', 'code_un' => '854'],
            ['name' => 'Burundi', 'code_alpha_2' => 'BI', 'code_alpha_3' => 'BDI', 'code_un' => '108'],
            ['name' => 'Cambodia', 'code_alpha_2' => 'KH', 'code_alpha_3' => 'KHM', 'code_un' => '116'],
            ['name' => 'Cameroon', 'code_alpha_2' => 'CM', 'code_alpha_3' => 'CMR', 'code_un' => '120'],
            ['name' => 'Canada', 'code_alpha_2' => 'CA', 'code_alpha_3' => 'CAN', 'code_un' => '124'],
            ['name' => 'Cape Verde', 'code_alpha_2' => 'CV', 'code_alpha_3' => 'CPV', 'code_un' => '132'],
            ['name' => 'Cayman Islands', 'code_alpha_2' => 'KY', 'code_alpha_3' => 'CYM', 'code_un' => '136'],
            ['name' => 'Central African Republic', 'code_alpha_2' => 'CF', 'code_alpha_3' => 'CAF', 'code_un' => '140'],
            ['name' => 'Chad', 'code_alpha_2' => 'TD', 'code_alpha_3' => 'TCD', 'code_un' => '148'],
            ['name' => 'Chile', 'code_alpha_2' => 'CL', 'code_alpha_3' => 'CHL', 'code_un' => '152'],
            ['name' => 'China', 'code_alpha_2' => 'CN', 'code_alpha_3' => 'CHN', 'code_un' => '156'],
            ['name' => 'Hong Kong, SAR China', 'code_alpha_2' => 'HK', 'code_alpha_3' => 'HKG', 'code_un' => '344'],
            ['name' => 'Macao, SAR China', 'code_alpha_2' => 'MO', 'code_alpha_3' => 'MAC', 'code_un' => '446'],
            ['name' => 'Christmas Island', 'code_alpha_2' => 'CX', 'code_alpha_3' => 'CXR', 'code_un' => '162'],
            ['name' => 'Cocos (Keeling) Islands', 'code_alpha_2' => 'CC', 'code_alpha_3' => 'CCK', 'code_un' => '166'],
            ['name' => 'Colombia', 'code_alpha_2' => 'CO', 'code_alpha_3' => 'COL', 'code_un' => '170'],
            ['name' => 'Comoros', 'code_alpha_2' => 'KM', 'code_alpha_3' => 'COM', 'code_un' => '174'],
            ['name' => 'Congo (Brazzaville)', 'code_alpha_2' => 'CG', 'code_alpha_3' => 'COG', 'code_un' => '178'],
            ['name' => 'Congo, (Kinshasa)', 'code_alpha_2' => 'CD', 'code_alpha_3' => 'COD', 'code_un' => '180'],
            ['name' => 'Cook Islands', 'code_alpha_2' => 'CK', 'code_alpha_3' => 'COK', 'code_un' => '184'],
            ['name' => 'Costa Rica', 'code_alpha_2' => 'CR', 'code_alpha_3' => 'CRI', 'code_un' => '188'],
            ['name' => "Côte d'Ivoire", 'code_alpha_2' => 'CI', 'code_alpha_3' => 'CIV', 'code_un' => '384'],
            ['name' => 'Croatia', 'code_alpha_2' => 'HR', 'code_alpha_3' => 'HRV', 'code_un' => '191'],
            ['name' => 'Cuba', 'code_alpha_2' => 'CU', 'code_alpha_3' => 'CUB', 'code_un' => '192'],
            ['name' => 'Cyprus', 'code_alpha_2' => 'CY', 'code_alpha_3' => 'CYP', 'code_un' => '196'],
            ['name' => 'Czech Republic', 'code_alpha_2' => 'CZ', 'code_alpha_3' => 'CZE', 'code_un' => '203'],
            ['name' => 'Denmark', 'code_alpha_2' => 'DK', 'code_alpha_3' => 'DNK', 'code_un' => '208'],
            ['name' => 'Djibouti', 'code_alpha_2' => 'DJ', 'code_alpha_3' => 'DJI', 'code_un' => '262'],
            ['name' => 'Dominica', 'code_alpha_2' => 'DM', 'code_alpha_3' => 'DMA', 'code_un' => '212'],
            ['name' => 'Dominican Republic', 'code_alpha_2' => 'DO', 'code_alpha_3' => 'DOM', 'code_un' => '214'],
            ['name' => 'Ecuador', 'code_alpha_2' => 'EC', 'code_alpha_3' => 'ECU', 'code_un' => '218'],
            ['name' => 'Egypt', 'code_alpha_2' => 'EG', 'code_alpha_3' => 'EGY', 'code_un' => '818'],
            ['name' => 'El Salvador', 'code_alpha_2' => 'SV', 'code_alpha_3' => 'SLV', 'code_un' => '222'],
            ['name' => 'Equatorial Guinea', 'code_alpha_2' => 'GQ', 'code_alpha_3' => 'GNQ', 'code_un' => '226'],
            ['name' => 'Eritrea', 'code_alpha_2' => 'ER', 'code_alpha_3' => 'ERI', 'code_un' => '232'],
            ['name' => 'Estonia', 'code_alpha_2' => 'EE', 'code_alpha_3' => 'EST', 'code_un' => '233'],
            ['name' => 'Ethiopia', 'code_alpha_2' => 'ET', 'code_alpha_3' => 'ETH', 'code_un' => '231'],
            ['name' => 'Falkland Islands (Malvinas)', 'code_alpha_2' => 'FK', 'code_alpha_3' => 'FLK', 'code_un' => '238'],
            ['name' => 'Faroe Islands', 'code_alpha_2' => 'FO', 'code_alpha_3' => 'FRO', 'code_un' => '234'],
            ['name' => 'Fiji', 'code_alpha_2' => 'FJ', 'code_alpha_3' => 'FJI', 'code_un' => '242'],
            ['name' => 'Finland', 'code_alpha_2' => 'FI', 'code_alpha_3' => 'FIN', 'code_un' => '246'],
            ['name' => 'France', 'code_alpha_2' => 'FR', 'code_alpha_3' => 'FRA', 'code_un' => '250'],
            ['name' => 'French Guiana', 'code_alpha_2' => 'GF', 'code_alpha_3' => 'GUF', 'code_un' => '254'],
            ['name' => 'French Polynesia', 'code_alpha_2' => 'PF', 'code_alpha_3' => 'PYF', 'code_un' => '258'],
            ['name' => 'French Southern Territories', 'code_alpha_2' => 'TF', 'code_alpha_3' => 'ATF', 'code_un' => '260'],
            ['name' => 'Gabon', 'code_alpha_2' => 'GA', 'code_alpha_3' => 'GAB', 'code_un' => '266'],
            ['name' => 'Gambia', 'code_alpha_2' => 'GM', 'code_alpha_3' => 'GMB', 'code_un' => '270'],
            ['name' => 'Georgia', 'code_alpha_2' => 'GE', 'code_alpha_3' => 'GEO', 'code_un' => '268'],
            ['name' => 'Germany', 'code_alpha_2' => 'DE', 'code_alpha_3' => 'DEU', 'code_un' => '276'],
            ['name' => 'Ghana', 'code_alpha_2' => 'GH', 'code_alpha_3' => 'GHA', 'code_un' => '288'],
            ['name' => 'Gibraltar', 'code_alpha_2' => 'GI', 'code_alpha_3' => 'GIB', 'code_un' => '292'],
            ['name' => 'Greece', 'code_alpha_2' => 'GR', 'code_alpha_3' => 'GRC', 'code_un' => '300'],
            ['name' => 'Greenland', 'code_alpha_2' => 'GL', 'code_alpha_3' => 'GRL', 'code_un' => '304'],
            ['name' => 'Grenada', 'code_alpha_2' => 'GD', 'code_alpha_3' => 'GRD', 'code_un' => '308'],
            ['name' => 'Guadeloupe', 'code_alpha_2' => 'GP', 'code_alpha_3' => 'GLP', 'code_un' => '312'],
            ['name' => 'Guam', 'code_alpha_2' => 'GU', 'code_alpha_3' => 'GUM', 'code_un' => '316'],
            ['name' => 'Guatemala', 'code_alpha_2' => 'GT', 'code_alpha_3' => 'GTM', 'code_un' => '320'],
            ['name' => 'Guernsey', 'code_alpha_2' => 'GG', 'code_alpha_3' => 'GGY', 'code_un' => '831'],
            ['name' => 'Guinea', 'code_alpha_2' => 'GN', 'code_alpha_3' => 'GIN', 'code_un' => '324'],
            ['name' => 'Guinea-Bissau', 'code_alpha_2' => 'GW', 'code_alpha_3' => 'GNB', 'code_un' => '624'],
            ['name' => 'Guyana', 'code_alpha_2' => 'GY', 'code_alpha_3' => 'GUY', 'code_un' => '328'],
            ['name' => 'Haiti', 'code_alpha_2' => 'HT', 'code_alpha_3' => 'HTI', 'code_un' => '332'],
            ['name' => 'Heard and Mcdonald Islands', 'code_alpha_2' => 'HM', 'code_alpha_3' => 'HMD', 'code_un' => '334'],
            ['name' => 'Holy See (Vatican City State)', 'code_alpha_2' => 'VA', 'code_alpha_3' => 'VAT', 'code_un' => '336'],
            ['name' => 'Honduras', 'code_alpha_2' => 'HN', 'code_alpha_3' => 'HND', 'code_un' => '340'],
            ['name' => 'Hungary', 'code_alpha_2' => 'HU', 'code_alpha_3' => 'HUN', 'code_un' => '348'],
            ['name' => 'Iceland', 'code_alpha_2' => 'IS', 'code_alpha_3' => 'ISL', 'code_un' => '352'],
            ['name' => 'India', 'code_alpha_2' => 'IN', 'code_alpha_3' => 'IND', 'code_un' => '356'],
            ['name' => 'Indonesia', 'code_alpha_2' => 'ID', 'code_alpha_3' => 'IDN', 'code_un' => '360'],
            ['name' => 'Iran', 'code_alpha_2' => 'IR', 'code_alpha_3' => 'IRN', 'code_un' => '364'],
            ['name' => 'Iraq', 'code_alpha_2' => 'IQ', 'code_alpha_3' => 'IRQ', 'code_un' => '368'],
            ['name' => 'Ireland', 'code_alpha_2' => 'IE', 'code_alpha_3' => 'IRL', 'code_un' => '372'],
            ['name' => 'Isle of Man', 'code_alpha_2' => 'IM', 'code_alpha_3' => 'IMN', 'code_un' => '833'],
            ['name' => 'Israel', 'code_alpha_2' => 'IL', 'code_alpha_3' => 'ISR', 'code_un' => '376'],
            ['name' => 'Italy', 'code_alpha_2' => 'IT', 'code_alpha_3' => 'ITA', 'code_un' => '380'],
            ['name' => 'Jamaica', 'code_alpha_2' => 'JM', 'code_alpha_3' => 'JAM', 'code_un' => '388'],
            ['name' => 'Japan', 'code_alpha_2' => 'JP', 'code_alpha_3' => 'JPN', 'code_un' => '392'],
            ['name' => 'Jersey', 'code_alpha_2' => 'JE', 'code_alpha_3' => 'JEY', 'code_un' => '832'],
            ['name' => 'Jordan', 'code_alpha_2' => 'JO', 'code_alpha_3' => 'JOR', 'code_un' => '400'],
            ['name' => 'Kazakhstan', 'code_alpha_2' => 'KZ', 'code_alpha_3' => 'KAZ', 'code_un' => '398'],
            ['name' => 'Kenya', 'code_alpha_2' => 'KE', 'code_alpha_3' => 'KEN', 'code_un' => '404'],
            ['name' => 'Kiribati', 'code_alpha_2' => 'KI', 'code_alpha_3' => 'KIR', 'code_un' => '296'],
            ['name' => 'Korea (North)', 'code_alpha_2' => 'KP', 'code_alpha_3' => 'PRK', 'code_un' => '408'],
            ['name' => 'Korea (South)', 'code_alpha_2' => 'KR', 'code_alpha_3' => 'KOR', 'code_un' => '410'],
            ['name' => 'Kuwait', 'code_alpha_2' => 'KW', 'code_alpha_3' => 'KWT', 'code_un' => '414'],
            ['name' => 'Kyrgyzstan', 'code_alpha_2' => 'KG', 'code_alpha_3' => 'KGZ', 'code_un' => '417'],
            ['name' => 'Lao PDR', 'code_alpha_2' => 'LA', 'code_alpha_3' => 'LAO', 'code_un' => '418'],
            ['name' => 'Latvia', 'code_alpha_2' => 'LV', 'code_alpha_3' => 'LVA', 'code_un' => '428'],
            ['name' => 'Lebanon', 'code_alpha_2' => 'LB', 'code_alpha_3' => 'LBN', 'code_un' => '422'],
            ['name' => 'Lesotho', 'code_alpha_2' => 'LS', 'code_alpha_3' => 'LSO', 'code_un' => '426'],
            ['name' => 'Liberia', 'code_alpha_2' => 'LR', 'code_alpha_3' => 'LBR', 'code_un' => '430'],
            ['name' => 'Libya', 'code_alpha_2' => 'LY', 'code_alpha_3' => 'LBY', 'code_un' => '434'],
            ['name' => 'Liechtenstein', 'code_alpha_2' => 'LI', 'code_alpha_3' => 'LIE', 'code_un' => '438'],
            ['name' => 'Lithuania', 'code_alpha_2' => 'LT', 'code_alpha_3' => 'LTU', 'code_un' => '440'],
            ['name' => 'Luxembourg', 'code_alpha_2' => 'LU', 'code_alpha_3' => 'LUX', 'code_un' => '442'],
            ['name' => 'Macedonia, Republic of', 'code_alpha_2' => 'MK', 'code_alpha_3' => 'MKD', 'code_un' => '807'],
            ['name' => 'Madagascar', 'code_alpha_2' => 'MG', 'code_alpha_3' => 'MDG', 'code_un' => '450'],
            ['name' => 'Malawi', 'code_alpha_2' => 'MW', 'code_alpha_3' => 'MWI', 'code_un' => '454'],
            ['name' => 'Malaysia', 'code_alpha_2' => 'MY', 'code_alpha_3' => 'MYS', 'code_un' => '458'],
            ['name' => 'Maldives', 'code_alpha_2' => 'MV', 'code_alpha_3' => 'MDV', 'code_un' => '462'],
            ['name' => 'Mali', 'code_alpha_2' => 'ML', 'code_alpha_3' => 'MLI', 'code_un' => '466'],
            ['name' => 'Malta', 'code_alpha_2' => 'MT', 'code_alpha_3' => 'MLT', 'code_un' => '470'],
            ['name' => 'Marshall Islands', 'code_alpha_2' => 'MH', 'code_alpha_3' => 'MHL', 'code_un' => '584'],
            ['name' => 'Martinique', 'code_alpha_2' => 'MQ', 'code_alpha_3' => 'MTQ', 'code_un' => '474'],
            ['name' => 'Mauritania', 'code_alpha_2' => 'MR', 'code_alpha_3' => 'MRT', 'code_un' => '478'],
            ['name' => 'Mauritius', 'code_alpha_2' => 'MU', 'code_alpha_3' => 'MUS', 'code_un' => '480'],
            ['name' => 'Mayotte', 'code_alpha_2' => 'YT', 'code_alpha_3' => 'MYT', 'code_un' => '175'],
            ['name' => 'Mexico', 'code_alpha_2' => 'MX', 'code_alpha_3' => 'MEX', 'code_un' => '484'],
            ['name' => 'Micronesia, Federated States of', 'code_alpha_2' => 'FM', 'code_alpha_3' => 'FSM', 'code_un' => '583'],
            ['name' => 'Moldova', 'code_alpha_2' => 'MD', 'code_alpha_3' => 'MDA', 'code_un' => '498'],
            ['name' => 'Monaco', 'code_alpha_2' => 'MC', 'code_alpha_3' => 'MCO', 'code_un' => '492'],
            ['name' => 'Mongolia', 'code_alpha_2' => 'MN', 'code_alpha_3' => 'MNG', 'code_un' => '496'],
            ['name' => 'Montenegro', 'code_alpha_2' => 'ME', 'code_alpha_3' => 'MNE', 'code_un' => '499'],
            ['name' => 'Montserrat', 'code_alpha_2' => 'MS', 'code_alpha_3' => 'MSR', 'code_un' => '500'],
            ['name' => 'Morocco', 'code_alpha_2' => 'MA', 'code_alpha_3' => 'MAR', 'code_un' => '504'],
            ['name' => 'Mozambique', 'code_alpha_2' => 'MZ', 'code_alpha_3' => 'MOZ', 'code_un' => '508'],
            ['name' => 'Myanmar', 'code_alpha_2' => 'MM', 'code_alpha_3' => 'MMR', 'code_un' => '104'],
            ['name' => 'Namibia', 'code_alpha_2' => 'NA', 'code_alpha_3' => 'NAM', 'code_un' => '516'],
            ['name' => 'Nauru', 'code_alpha_2' => 'NR', 'code_alpha_3' => 'NRU', 'code_un' => '520'],
            ['name' => 'Nepal', 'code_alpha_2' => 'NP', 'code_alpha_3' => 'NPL', 'code_un' => '524'],
            ['name' => 'Netherlands', 'code_alpha_2' => 'NL', 'code_alpha_3' => 'NLD', 'code_un' => '528'],
            ['name' => 'Netherlands Antilles', 'code_alpha_2' => 'AN', 'code_alpha_3' => 'ANT', 'code_un' => '530'],
            ['name' => 'New Caledonia', 'code_alpha_2' => 'NC', 'code_alpha_3' => 'NCL', 'code_un' => '540'],
            ['name' => 'New Zealand', 'code_alpha_2' => 'NZ', 'code_alpha_3' => 'NZL', 'code_un' => '554'],
            ['name' => 'Nicaragua', 'code_alpha_2' => 'NI', 'code_alpha_3' => 'NIC', 'code_un' => '558'],
            ['name' => 'Niger', 'code_alpha_2' => 'NE', 'code_alpha_3' => 'NER', 'code_un' => '562'],
            ['name' => 'Nigeria', 'code_alpha_2' => 'NG', 'code_alpha_3' => 'NGA', 'code_un' => '566'],
            ['name' => 'Niue', 'code_alpha_2' => 'NU', 'code_alpha_3' => 'NIU', 'code_un' => '570'],
            ['name' => 'Norfolk Island', 'code_alpha_2' => 'NF', 'code_alpha_3' => 'NFK', 'code_un' => '574'],
            ['name' => 'Northern Mariana Islands', 'code_alpha_2' => 'MP', 'code_alpha_3' => 'MNP', 'code_un' => '580'],
            ['name' => 'Norway', 'code_alpha_2' => 'NO', 'code_alpha_3' => 'NOR', 'code_un' => '578'],
            ['name' => 'Oman', 'code_alpha_2' => 'OM', 'code_alpha_3' => 'OMN', 'code_un' => '512'],
            ['name' => 'Pakistan', 'code_alpha_2' => 'PK', 'code_alpha_3' => 'PAK', 'code_un' => '586'],
            ['name' => 'Palau', 'code_alpha_2' => 'PW', 'code_alpha_3' => 'PLW', 'code_un' => '585'],
            ['name' => 'Palestinian Territory', 'code_alpha_2' => 'PS', 'code_alpha_3' => 'PSE', 'code_un' => '275'],
            ['name' => 'Panama', 'code_alpha_2' => 'PA', 'code_alpha_3' => 'PAN', 'code_un' => '591'],
            ['name' => 'Papua New Guinea', 'code_alpha_2' => 'PG', 'code_alpha_3' => 'PNG', 'code_un' => '598'],
            ['name' => 'Paraguay', 'code_alpha_2' => 'PY', 'code_alpha_3' => 'PRY', 'code_un' => '600'],
            ['name' => 'Peru', 'code_alpha_2' => 'PE', 'code_alpha_3' => 'PER', 'code_un' => '604'],
            ['name' => 'Philippines', 'code_alpha_2' => 'PH', 'code_alpha_3' => 'PHL', 'code_un' => '608'],
            ['name' => 'Pitcairn', 'code_alpha_2' => 'PN', 'code_alpha_3' => 'PCN', 'code_un' => '612'],
            ['name' => 'Poland', 'code_alpha_2' => 'PL', 'code_alpha_3' => 'POL', 'code_un' => '616'],
            ['name' => 'Portugal', 'code_alpha_2' => 'PT', 'code_alpha_3' => 'PRT', 'code_un' => '620'],
            ['name' => 'Puerto Rico', 'code_alpha_2' => 'PR', 'code_alpha_3' => 'PRI', 'code_un' => '630'],
            ['name' => 'Qatar', 'code_alpha_2' => 'QA', 'code_alpha_3' => 'QAT', 'code_un' => '634'],
            ['name' => 'Réunion', 'code_alpha_2' => 'RE', 'code_alpha_3' => 'REU', 'code_un' => '638'],
            ['name' => 'Romania', 'code_alpha_2' => 'RO', 'code_alpha_3' => 'ROU', 'code_un' => '642'],
            ['name' => 'Russian Federation', 'code_alpha_2' => 'RU', 'code_alpha_3' => 'RUS', 'code_un' => '643'],
            ['name' => 'Rwanda', 'code_alpha_2' => 'RW', 'code_alpha_3' => 'RWA', 'code_un' => '646'],
            ['name' => 'Saint-Barthélemy', 'code_alpha_2' => 'BL', 'code_alpha_3' => 'BLM', 'code_un' => '652'],
            ['name' => 'Saint Helena', 'code_alpha_2' => 'SH', 'code_alpha_3' => 'SHN', 'code_un' => '654'],
            ['name' => 'Saint Kitts and Nevis', 'code_alpha_2' => 'KN', 'code_alpha_3' => 'KNA', 'code_un' => '659'],
            ['name' => 'Saint Lucia', 'code_alpha_2' => 'LC', 'code_alpha_3' => 'LCA', 'code_un' => '662'],
            ['name' => 'Saint-Martin (French part)', 'code_alpha_2' => 'MF', 'code_alpha_3' => 'MAF', 'code_un' => '663'],
            ['name' => 'Saint Pierre and Miquelon', 'code_alpha_2' => 'PM', 'code_alpha_3' => 'SPM', 'code_un' => '666'],
            ['name' => 'Saint Vincent and Grenadines', 'code_alpha_2' => 'VC', 'code_alpha_3' => 'VCT', 'code_un' => '670'],
            ['name' => 'Samoa', 'code_alpha_2' => 'WS', 'code_alpha_3' => 'WSM', 'code_un' => '882'],
            ['name' => 'San Marino', 'code_alpha_2' => 'SM', 'code_alpha_3' => 'SMR', 'code_un' => '674'],
            ['name' => 'Sao Tome and Principe', 'code_alpha_2' => 'ST', 'code_alpha_3' => 'STP', 'code_un' => '678'],
            ['name' => 'Saudi Arabia', 'code_alpha_2' => 'SA', 'code_alpha_3' => 'SAU', 'code_un' => '682'],
            ['name' => 'Senegal', 'code_alpha_2' => 'SN', 'code_alpha_3' => 'SEN', 'code_un' => '686'],
            ['name' => 'Serbia', 'code_alpha_2' => 'RS', 'code_alpha_3' => 'SRB', 'code_un' => '688'],
            ['name' => 'Seychelles', 'code_alpha_2' => 'SC', 'code_alpha_3' => 'SYC', 'code_un' => '690'],
            ['name' => 'Sierra Leone', 'code_alpha_2' => 'SL', 'code_alpha_3' => 'SLE', 'code_un' => '694'],
            ['name' => 'Singapore', 'code_alpha_2' => 'SG', 'code_alpha_3' => 'SGP', 'code_un' => '702'],
            ['name' => 'Slovakia', 'code_alpha_2' => 'SK', 'code_alpha_3' => 'SVK', 'code_un' => '703'],
            ['name' => 'Slovenia', 'code_alpha_2' => 'SI', 'code_alpha_3' => 'SVN', 'code_un' => '705'],
            ['name' => 'Solomon Islands', 'code_alpha_2' => 'SB', 'code_alpha_3' => 'SLB', 'code_un' => '090'],
            ['name' => 'Somalia', 'code_alpha_2' => 'SO', 'code_alpha_3' => 'SOM', 'code_un' => '706'],
            ['name' => 'South Africa', 'code_alpha_2' => 'ZA', 'code_alpha_3' => 'ZAF', 'code_un' => '710'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code_alpha_2' => 'GS', 'code_alpha_3' => 'SGS', 'code_un' => '239'],
            ['name' => 'South Sudan', 'code_alpha_2' => 'SS', 'code_alpha_3' => 'SSD', 'code_un' => '728'],
            ['name' => 'Spain', 'code_alpha_2' => 'ES', 'code_alpha_3' => 'ESP', 'code_un' => '724'],
            ['name' => 'Sri Lanka', 'code_alpha_2' => 'LK', 'code_alpha_3' => 'LKA', 'code_un' => '144'],
            ['name' => 'Sudan', 'code_alpha_2' => 'SD', 'code_alpha_3' => 'SDN', 'code_un' => '736'],
            ['name' => 'Suriname', 'code_alpha_2' => 'SR', 'code_alpha_3' => 'SUR', 'code_un' => '740'],
            ['name' => 'Svalbard and Jan Mayen Islands', 'code_alpha_2' => 'SJ', 'code_alpha_3' => 'SJM', 'code_un' => '744'],
            ['name' => 'Swaziland', 'code_alpha_2' => 'SZ', 'code_alpha_3' => 'SWZ', 'code_un' => '748'],
            ['name' => 'Sweden', 'code_alpha_2' => 'SE', 'code_alpha_3' => 'SWE', 'code_un' => '752'],
            ['name' => 'Switzerland', 'code_alpha_2' => 'CH', 'code_alpha_3' => 'CHE', 'code_un' => '756'],
            ['name' => 'Syrian Arab Republic (Syria)', 'code_alpha_2' => 'SY', 'code_alpha_3' => 'SYR', 'code_un' => '760'],
            ['name' => 'Taiwan, Republic of China', 'code_alpha_2' => 'TW', 'code_alpha_3' => 'TWN', 'code_un' => '158'],
            ['name' => 'Tajikistan', 'code_alpha_2' => 'TJ', 'code_alpha_3' => 'TJK', 'code_un' => '762'],
            ['name' => 'Tanzania, United Republic of', 'code_alpha_2' => 'TZ', 'code_alpha_3' => 'TZA', 'code_un' => '834'],
            ['name' => 'Thailand', 'code_alpha_2' => 'TH', 'code_alpha_3' => 'THA', 'code_un' => '764'],
            ['name' => 'Timor-Leste', 'code_alpha_2' => 'TL', 'code_alpha_3' => 'TLS', 'code_un' => '626'],
            ['name' => 'Togo', 'code_alpha_2' => 'TG', 'code_alpha_3' => 'TGO', 'code_un' => '768'],
            ['name' => 'Tokelau', 'code_alpha_2' => 'TK', 'code_alpha_3' => 'TKL', 'code_un' => '772'],
            ['name' => 'Tonga', 'code_alpha_2' => 'TO', 'code_alpha_3' => 'TON', 'code_un' => '776'],
            ['name' => 'Trinidad and Tobago', 'code_alpha_2' => 'TT', 'code_alpha_3' => 'TTO', 'code_un' => '780'],
            ['name' => 'Tunisia', 'code_alpha_2' => 'TN', 'code_alpha_3' => 'TUN', 'code_un' => '788'],
            ['name' => 'Turkey', 'code_alpha_2' => 'TR', 'code_alpha_3' => 'TUR', 'code_un' => '792'],
            ['name' => 'Turkmenistan', 'code_alpha_2' => 'TM', 'code_alpha_3' => 'TKM', 'code_un' => '795'],
            ['name' => 'Turks and Caicos Islands', 'code_alpha_2' => 'TC', 'code_alpha_3' => 'TCA', 'code_un' => '796'],
            ['name' => 'Tuvalu', 'code_alpha_2' => 'TV', 'code_alpha_3' => 'TUV', 'code_un' => '798'],
            ['name' => 'Uganda', 'code_alpha_2' => 'UG', 'code_alpha_3' => 'UGA', 'code_un' => '800'],
            ['name' => 'Ukraine', 'code_alpha_2' => 'UA', 'code_alpha_3' => 'UKR', 'code_un' => '804'],
            ['name' => 'United Arab Emirates', 'code_alpha_2' => 'AE', 'code_alpha_3' => 'ARE', 'code_un' => '784'],
            ['name' => 'United Kingdom', 'code_alpha_2' => 'GB', 'code_alpha_3' => 'GBR', 'code_un' => '826'],
            ['name' => 'United States of America', 'code_alpha_2' => 'US', 'code_alpha_3' => 'USA', 'code_un' => '840'],
            ['name' => 'US Minor Outlying Islands', 'code_alpha_2' => 'UM', 'code_alpha_3' => 'UMI', 'code_un' => '581'],
            ['name' => 'Uruguay', 'code_alpha_2' => 'UY', 'code_alpha_3' => 'URY', 'code_un' => '858'],
            ['name' => 'Uzbekistan', 'code_alpha_2' => 'UZ', 'code_alpha_3' => 'UZB', 'code_un' => '860'],
            ['name' => 'Vanuatu', 'code_alpha_2' => 'VU', 'code_alpha_3' => 'VUT', 'code_un' => '548'],
            ['name' => 'Venezuela (Bolivarian Republic)', 'code_alpha_2' => 'VE', 'code_alpha_3' => 'VEN', 'code_un' => '862'],
            ['name' => 'Viet Nam', 'code_alpha_2' => 'VN', 'code_alpha_3' => 'VNM', 'code_un' => '704'],
            ['name' => 'Virgin Islands, US', 'code_alpha_2' => 'VI', 'code_alpha_3' => 'VIR', 'code_un' => '850'],
            ['name' => 'Wallis and Futuna Islands', 'code_alpha_2' => 'WF', 'code_alpha_3' => 'WLF', 'code_un' => '876'],
            ['name' => 'Western Sahara', 'code_alpha_2' => 'EH', 'code_alpha_3' => 'ESH', 'code_un' => '732'],
            ['name' => 'Yemen', 'code_alpha_2' => 'YE', 'code_alpha_3' => 'YEM', 'code_un' => '887'],
            ['name' => 'Zambia', 'code_alpha_2' => 'ZM', 'code_alpha_3' => 'ZMB', 'code_un' => '894'],
            ['name' => 'Zimbabwe', 'code_alpha_2' => 'ZW', 'code_alpha_3' => 'ZWE', 'code_un' => '716']
        ];

        foreach ($data as $row) {
            Country::factory()->create($row);
        }
    }
}